theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  breadcrumb:
    position: none
  summary:
    position: hero
  posts:
    date_format: "2006"
    index:
      show_categories: false
      show_author: false
      show_description: true
      truncate_description: 0
      layout: grid